repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
        exclude: /generated
      - id: destroyed-symlinks
      - id: fix-byte-order-marker
      - id: check-yaml
        exclude: /templates/
        args: [--allow-multiple-documents]
  - repo: https://github.com/pre-commit/pre-commit
    rev: v3.4.0
    hooks:
      - id: terraform-fmt
      - id: helmlint
